# Generated by Django 6.0.8 on 2026-09-19 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitbackend', '2029_09_084500_add_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('action_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done')], default='open', max_length=16)),
                ('source_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='orbitbackend.chunk')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='orbitbackend.topic')),
            ],
            options={
                'db_table': 'action_items',
            },
        ),
    ]
