"""
Django settings for orbit_app project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import os

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
try:
    environ.Env.read_env(BASE_DIR / '.env')
except FileNotFoundError:
    # Local self-tests / offline runs without a .env file fall back to
    # safe defaults below instead of crashing at import time.
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-sentinel-dev-key-12345')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',
    'corsheaders',
    'django_celery_beat',
    'django_celery_results',
    'orbit_app.core',
    'orbit_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'orbit_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orbit_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Local self-tests fall back to sqlite (or DATABASE_URL) when Postgres env
# vars / .env are absent; production sets POSTGRES_* (or DATABASE_URL).

DATABASES = {'default': environ.Env.db_url_config(
    env('DATABASE_URL', default='sqlite:///db.sqlite3'),
)}

if not DATABASES['default'].get('ENGINE'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

if all(k in os.environ for k in ('POSTGRES_DB', 'POSTGRES_USER', 'POSTGRES_PASSWORD')) or \
        any(k in os.environ for k in ('POSTGRES_DB', 'POSTGRES_USER', 'POSTGRES_PASSWORD',
                                       'POSTGRES_HOST', 'POSTGRES_PORT')):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('POSTGRES_DB', default='orbit'),
            'USER': env('POSTGRES_USER', default='orbit'),
            'PASSWORD': env('POSTGRES_PASSWORD', default='orbit'),
            'HOST': env('POSTGRES_HOST', default='localhost'),
            'PORT': env('POSTGRES_PORT', default='5432'),
        }
    }


def _postgres_reachable(host, port, timeout=1.0):
    """Best-effort TCP probe so tests/CI fall back to sqlite when PG is down."""
    import socket

    try:
        with socket.create_connection((host, int(port)), timeout=timeout):
            return True
    except Exception:
        return False


def _should_use_sqlite_fallback():
    # Explicit opt-in always wins (local dev / CI without Postgres).
    if os.environ.get('ORBIT_USE_SQLITE', '').lower() in ('1', 'true', 'yes'):
        return True
    # Explicit DATABASE_URL means the operator chose the backend; respect it.
    if os.environ.get('DATABASE_URL'):
        return False
    engine = (DATABASES.get('default', {}).get('ENGINE') or '')
    if 'postgresql' not in engine:
        return False
    # Fall back to sqlite whenever Postgres is unreachable (tests, migrate,
    # shell, runserver offline). Production with a live PG is unaffected
    # because the probe succeeds and Postgres is kept.
    cfg = DATABASES['default']
    return not _postgres_reachable(cfg.get('HOST') or 'localhost', cfg.get('PORT') or 5432)


if _should_use_sqlite_fallback():
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'orbit_app.core.exception_handler.api_exception_handler',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'orbit_app.core.auth.ApiKeyAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}


# CORS
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])


# Celery
# https://docs.celeryq.dev/en/stable/userguide/configuration.html

CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE


# sentinel-backend-service: external meeting / contradiction / pgvector service.
# Timeout is generous because Render free instances sleep and cold-start slowly.
SENTINEL_SERVICE_URL = env('SENTINEL_SERVICE_URL', default='https://orbit-e873.onrender.com')
SENTINEL_SERVICE_API_KEY = env('SENTINEL_SERVICE_API_KEY', default='')
SENTINEL_SERVICE_TIMEOUT = env.int('SENTINEL_SERVICE_TIMEOUT', default=90)

# API keys accepted by this backend's own API (comma-separated). Empty = no key works.
ORBIT_API_KEYS = env.list('ORBIT_API_KEYS', default=[])
