# Generated by Django 6.0.8 on 2026-09-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('meeting_transcript', 'Meeting Transcript'), ('pdf', 'PDF')], max_length=32)),
                ('sender', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('raw_text', models.TextField()),
                ('authority_level', models.CharField(choices=[('official', 'Official'), ('general', 'General')], max_length=16)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
